version: "3.8"

services:
  admin-app:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    container_name: admin-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8088:80"
    volumes:
      - ./admin:/var/www/admin
    networks:
      - local-net   # 本家MySQLがいるネットワーク

networks:
  local-net:
    external: true
    name: m-conlocalhostnet_local-net